-- Laboratory Experiment Tracking System
-- PostgreSQL 15 schema

-- =========================
-- ENUMS
-- =========================

CREATE TYPE project_status AS ENUM (
  'planning',
  'active',
  'completed',
  'cancelled'
);

CREATE TYPE experiment_status AS ENUM (
  'planning',
  'active',
  'completed',
  'archived',
  'cancelled'
);

CREATE TYPE measurement_type AS ENUM (
  'numeric',
  'categorical',
  'text'
);

CREATE TYPE sample_status AS ENUM (
  'available',
  'depleted',
  'expired',
  'contaminated',
  'destroyed',
  'archived'
);

-- =========================
-- RESEARCHERS & PROJECTS
-- =========================

CREATE TABLE researchers (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL CHECK (length(trim(name)) > 0),
  email TEXT NOT NULL UNIQUE CHECK (length(trim(email)) > 0),
  phone TEXT,
  lab_role TEXT NOT NULL CHECK (length(trim(lab_role)) > 0),
  contact_details JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE projects (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL CHECK (length(trim(title)) > 0),
  description TEXT,
  status project_status NOT NULL DEFAULT 'planning',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE researchers_projects (
  researcher_id INT NOT NULL REFERENCES researchers(id) ON DELETE RESTRICT,
  project_id INT NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  role TEXT NOT NULL CHECK (length(trim(role)) > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (researcher_id, project_id)
);

-- =========================
-- EXPERIMENTS (VERSIONED)
-- =========================

CREATE TABLE experiments (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  version INT NOT NULL DEFAULT 1 CHECK (version >= 1),
  is_current BOOLEAN NOT NULL DEFAULT TRUE,

  project_id INT NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,

  title TEXT NOT NULL CHECK (length(trim(title)) > 0),
  hypothesis TEXT,

  start_date TIMESTAMPTZ,
  end_date TIMESTAMPTZ,

  status experiment_status NOT NULL DEFAULT 'planning',

  approved_by_researcher_id INT REFERENCES researchers(id) ON DELETE RESTRICT,
  approved_at TIMESTAMPTZ,

  completed_by_researcher_id INT REFERENCES researchers(id) ON DELETE RESTRICT,
  completed_at TIMESTAMPTZ,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  PRIMARY KEY (id, version),

  CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date),
  CHECK (
    (approved_by_researcher_id IS NULL AND approved_at IS NULL)
    OR
    (approved_by_researcher_id IS NOT NULL AND approved_at IS NOT NULL)
  ),
  CHECK (
    (completed_by_researcher_id IS NULL AND completed_at IS NULL)
    OR
    (completed_by_researcher_id IS NOT NULL AND completed_at IS NOT NULL)
  ),
  CHECK (
    status <> 'completed'
    OR (completed_by_researcher_id IS NOT NULL AND completed_at IS NOT NULL)
  )
);

CREATE UNIQUE INDEX idx_experiments_one_current_version
ON experiments (id)
WHERE is_current = TRUE;

CREATE INDEX idx_experiments_project_status
ON experiments (project_id, status);

-- Researchers who directly participate in a specific experiment version.
CREATE TABLE experiments_researchers (
  experiment_id INT NOT NULL,
  experiment_version INT NOT NULL,
  researcher_id INT NOT NULL REFERENCES researchers(id) ON DELETE RESTRICT,
  role TEXT NOT NULL CHECK (length(trim(role)) > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  PRIMARY KEY (experiment_id, experiment_version, researcher_id),

  FOREIGN KEY (experiment_id, experiment_version)
    REFERENCES experiments(id, version)
    ON DELETE RESTRICT
);

-- =========================
-- EXPERIMENT RELATIONSHIPS (GRAPH)
-- =========================

CREATE TABLE experiment_relationships (
  parent_experiment_id INT NOT NULL,
  parent_experiment_version INT NOT NULL,
  child_experiment_id INT NOT NULL,
  child_experiment_version INT NOT NULL,
  relationship_type TEXT NOT NULL CHECK (length(trim(relationship_type)) > 0),
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  PRIMARY KEY (
    parent_experiment_id,
    parent_experiment_version,
    child_experiment_id,
    child_experiment_version,
    relationship_type
  ),

  FOREIGN KEY (parent_experiment_id, parent_experiment_version)
    REFERENCES experiments(id, version)
    ON DELETE RESTRICT,

  FOREIGN KEY (child_experiment_id, child_experiment_version)
    REFERENCES experiments(id, version)
    ON DELETE RESTRICT,

  CHECK (
    parent_experiment_id <> child_experiment_id
    OR parent_experiment_version <> child_experiment_version
  )
);

CREATE INDEX idx_experiment_relationships_child
ON experiment_relationships (child_experiment_id, child_experiment_version);

-- =========================
-- SAMPLES
-- =========================

CREATE TABLE samples (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sample_identifier TEXT NOT NULL UNIQUE CHECK (length(trim(sample_identifier)) > 0),
  specimen_type TEXT NOT NULL CHECK (length(trim(specimen_type)) > 0),

  collected_at TIMESTAMPTZ NOT NULL,
  storage_location TEXT NOT NULL CHECK (length(trim(storage_location)) > 0),

  status sample_status NOT NULL DEFAULT 'available',
  expiry_date TIMESTAMPTZ,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CHECK (expiry_date IS NULL OR expiry_date >= collected_at)
);

CREATE INDEX idx_samples_status_expiry
ON samples (status, expiry_date);

-- Optional storage condition history. This is not a full chain-of-custody model.
CREATE TABLE sample_storage_conditions (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sample_id INT NOT NULL REFERENCES samples(id) ON DELETE RESTRICT,
  recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  storage_location TEXT NOT NULL CHECK (length(trim(storage_location)) > 0),
  temperature_celsius NUMERIC(8, 3),
  humidity_percent NUMERIC(5, 2),
  notes TEXT,

  CHECK (humidity_percent IS NULL OR (humidity_percent >= 0 AND humidity_percent <= 100))
);

CREATE INDEX idx_sample_storage_conditions_sample_time
ON sample_storage_conditions (sample_id, recorded_at DESC);

-- =========================
-- SAMPLE RELATIONSHIPS (GRAPH)
-- =========================

CREATE TABLE sample_relationships (
  parent_sample_id INT NOT NULL REFERENCES samples(id) ON DELETE RESTRICT,
  child_sample_id INT NOT NULL REFERENCES samples(id) ON DELETE RESTRICT,
  relationship_type TEXT NOT NULL CHECK (length(trim(relationship_type)) > 0),
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  PRIMARY KEY (parent_sample_id, child_sample_id, relationship_type),

  CHECK (parent_sample_id <> child_sample_id)
);

CREATE INDEX idx_sample_relationships_child
ON sample_relationships (child_sample_id);

-- =========================
-- EXPERIMENTS <-> SAMPLES (WITH CONTEXT)
-- =========================

CREATE TABLE experiments_samples (
  experiment_id INT NOT NULL,
  experiment_version INT NOT NULL,
  sample_id INT NOT NULL REFERENCES samples(id) ON DELETE RESTRICT,

  role TEXT,
  quantity NUMERIC(18, 6),
  quantity_unit TEXT,
  preparation_notes TEXT,
  notes TEXT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  PRIMARY KEY (experiment_id, experiment_version, sample_id),

  FOREIGN KEY (experiment_id, experiment_version)
    REFERENCES experiments(id, version)
    ON DELETE RESTRICT,

  CHECK (quantity IS NULL OR quantity > 0),
  CHECK (
    (quantity IS NULL AND quantity_unit IS NULL)
    OR
    (quantity IS NOT NULL AND quantity_unit IS NOT NULL AND length(trim(quantity_unit)) > 0)
  )
);

CREATE INDEX idx_experiments_samples_sample
ON experiments_samples (sample_id);

-- =========================
-- MEASUREMENT DEFINITIONS
-- =========================

CREATE TABLE measurement_definitions (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL CHECK (length(trim(name)) > 0),
  value_type measurement_type NOT NULL,
  description TEXT,
  default_unit TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  UNIQUE (name),
  UNIQUE (id, value_type)
);

-- Optional allowed values for categorical measurement definitions.
CREATE TABLE measurement_definition_allowed_values (
  measurement_definition_id INT NOT NULL REFERENCES measurement_definitions(id) ON DELETE CASCADE,
  allowed_value TEXT NOT NULL CHECK (length(trim(allowed_value)) > 0),
  PRIMARY KEY (measurement_definition_id, allowed_value)
);

-- =========================
-- LAB DEVICES
-- =========================

CREATE TABLE lab_devices (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_identifier TEXT NOT NULL UNIQUE CHECK (length(trim(device_identifier)) > 0),
  name TEXT NOT NULL CHECK (length(trim(name)) > 0),
  device_type TEXT,
  manufacturer TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- =========================
-- MEASUREMENTS (VERSIONED, HIGH-VOLUME)
-- =========================

CREATE TABLE measurements (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  version INT NOT NULL DEFAULT 1 CHECK (version >= 1),
  is_current BOOLEAN NOT NULL DEFAULT TRUE,

  experiment_id INT NOT NULL,
  experiment_version INT NOT NULL,
  sample_id INT,

  measurement_definition_id INT NOT NULL,
  type measurement_type NOT NULL,

  recorded_at TIMESTAMPTZ NOT NULL,
  notes TEXT,

  -- Polymorphic values. CHECK constraints below enforce one shape per type.
  numeric_value DOUBLE PRECISION,
  unit TEXT,

  categorical_value TEXT,
  text_value TEXT,

  -- Provenance
  recorded_by_researcher_id INT NOT NULL REFERENCES researchers(id) ON DELETE RESTRICT,
  device_id INT REFERENCES lab_devices(id) ON DELETE RESTRICT,

  corrected_from_measurement_id INT,
  corrected_from_measurement_version INT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  PRIMARY KEY (id, version),

  FOREIGN KEY (experiment_id, experiment_version)
    REFERENCES experiments(id, version)
    ON DELETE RESTRICT,

  -- If sample_id is present, it must be linked to the same experiment version.
  FOREIGN KEY (experiment_id, experiment_version, sample_id)
    REFERENCES experiments_samples(experiment_id, experiment_version, sample_id)
    ON DELETE RESTRICT,

  FOREIGN KEY (measurement_definition_id, type)
    REFERENCES measurement_definitions(id, value_type)
    ON DELETE RESTRICT,

  FOREIGN KEY (corrected_from_measurement_id, corrected_from_measurement_version)
    REFERENCES measurements(id, version)
    ON DELETE RESTRICT,

  CHECK (
    (
      type = 'numeric'
      AND numeric_value IS NOT NULL
      AND unit IS NOT NULL
      AND length(trim(unit)) > 0
      AND categorical_value IS NULL
      AND text_value IS NULL
    )
    OR
    (
      type = 'categorical'
      AND categorical_value IS NOT NULL
      AND length(trim(categorical_value)) > 0
      AND numeric_value IS NULL
      AND unit IS NULL
      AND text_value IS NULL
    )
    OR
    (
      type = 'text'
      AND text_value IS NOT NULL
      AND length(trim(text_value)) > 0
      AND numeric_value IS NULL
      AND unit IS NULL
      AND categorical_value IS NULL
    )
  ),

  CHECK (
    (corrected_from_measurement_id IS NULL AND corrected_from_measurement_version IS NULL)
    OR
    (corrected_from_measurement_id IS NOT NULL AND corrected_from_measurement_version IS NOT NULL)
  ),

  CHECK (
    corrected_from_measurement_id IS NULL
    OR corrected_from_measurement_id <> id
    OR corrected_from_measurement_version <> version
  )
);

CREATE UNIQUE INDEX idx_measurements_one_current_version
ON measurements (id)
WHERE is_current = TRUE;

CREATE INDEX idx_measurements_experiment_time
ON measurements (experiment_id, experiment_version, recorded_at DESC);

CREATE INDEX idx_measurements_sample_time
ON measurements (sample_id, recorded_at DESC)
WHERE sample_id IS NOT NULL;

CREATE INDEX idx_measurements_definition_time
ON measurements (measurement_definition_id, recorded_at DESC);

CREATE INDEX idx_measurements_type
ON measurements (type);

CREATE INDEX idx_measurements_recorded_by
ON measurements (recorded_by_researcher_id);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;